### ISSUE TITLE
Blockchain Class Api Problem

### ISSUE THREAD

**Issue by Rezker** [blockchain/api-v1-client-php#17]
Hi,
Please help to resolve this issue !

require('lib/Blockchain.php');
$Blockchain = new \Blockchain\Blockchain("my_api_code");
$Blockchain->Wallet->credentials('id_blockchain', 'password', 'second_pass');
$address = $Blockchain->Wallet->getNewAddress($label=null);
echo $address;

Every time i execute the script, i get this error message:
( ! ) Fatal error: Class 'Blockchain\Create\Create' not found in \lib\Blockchain.php on line 65

Please try to fix this issue !
Thank's.

**Comment by clarkmoody** [comment]
Did you install the library with Composer?
