### ISSUE TITLE
API control for new wallets

### ISSUE THREAD

**Issue by riartem** [blockchain/api-v1-client-php#19]
Hello, dear developers.
Maybe, for wallets, created with API, should allow remote access with API and add callback url?
It helps to do without creating a "virtual" redirect wallets in some cases.
![](http://i.imgur.com/0T0lLoH.png)

Thank you

**Comment by KMHouk** [comment]
Hi,

For non-php library related issues, please open a ticket at https://blockchain.zendesk.com/ 

Thanks,
Kevin
