### ISSUE TITLE
my server's ip got blocked from blockchain?

### ISSUE THREAD

**Issue by mikedpid** [blockchain/api-v1-client-php#22]
i was just using the receive API and the wallet api in the callback.php and today when i went testing i got an error saying access denied and that my server's ip got banned.
i didnt send that many requests, just few for testing, i didnt exceed more than 50requests/day.

Error 1006 Ray ID: 1ebedb7c903a0d31 • 2015-05-25 05:32:01 UTC
Access denied
What happened?
The owner of this website (blockchain.info) has banned your IP address (162.213.255.32).

**Comment by mikelsx** [comment]
edit: Jade from support desk fixed it. thanks
