### ISSUE TITLE
autoload_real.php missing

### ISSUE THREAD

**Issue by athanar** [blockchain/api-v1-client-php#23]
Hi! Since Sunday 21st June, my call to api don't work anymore, beacause of a missing file : autoload_real.php who is declared in autoload.php...

Warning: require_once(/home/pesobangoa/www/wp-content/plugins/usdtobtc/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in /home/pesobangoa/www/wp-content/plugins/usdtobtc/vendor/autoload.php on line 5

My code is like this : 
function my_task_function() {
    require_once('src/Blockchain.php');
        require 'vendor/autoload.php';
    $api_key = get_option( 'usd_to_btc_api_key');
        $Blockchain = new \Blockchain\Blockchain('01aec668-8739-462c-93c2-25a13318457b');
    ...

And in autoload.php : 
<?php

// autoload.php @generated by Composer

require_once **DIR** . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit1d4d330dfb8c69b029aecf3be332a5f1::getLoader();

But there's no autoload_real.php on my server, how can i got it?

Thanks a lot.
Cédric.

**Comment by clarkmoody** [comment]
Are you using Composer to install the API library?

**Comment by athanar** [comment]
Hi! 

Thanks for your help.
Yes that was it, some files have been remove :/

I put them again but now i have this error : 
Fatal error: Class 'Blockchain\Create\Create' not found in Blockchain.php on line 65

Any ideas?
Thanks

**Comment by athanar** [comment]
I progress with read other issues here.
Now i have a permission denied (i put my api key in constructor).

Fatal error: Uncaught exception 'Blockchain\Exception\Error' with message 'Unable to decode JSON response from Blockchain: <!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <title>Access denied | blockchain.info used CloudFlare to restrict access</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" /> <!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.er in /home/pesobangoa/www/wp-content/plugins/usdtobtc/src/Blockchain.php on line 130

Cédric
