### ISSUE TITLE
Listing all transactions of a certain address

### ISSUE THREAD

**Issue by frdho** [blockchain/api-v1-client-php#27]
Hello,

I'm trying to print out an overview of all transactions done to a specific address, but no success so far.

I've gathered the info of the address, but the transactions are stored in an array (as written in the documentations), and can't get them out.

$limit = 50;
$offset = 0;
$address = "xxx";
$address_info = $Blockchain->Explorer->getAddress($address, $limit, $offset);
echo $address_info->n_tx; //just as a test, this works

$transactions = $address_info->transactions; //no error here
echo $transactions->version;

The last line of code throws this error: "Trying to get property of non-object". echo $transactions[0] also doesn't work.

Any ideas?

**Comment by alecalve** [comment]
Try this
```php
$limit = 50;
$offset = 0;
$address = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa";
$address_info = $Blockchain->Explorer->getAddress($address, $limit, $offset);
echo $address_info->transactions[0]->version;
```

It should output ```1```

**Comment by SPikeVanz** [comment]
$limit = 50;
$offset = 1;
$address = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa";
$address_info = $Blockchain->Explorer->getAddress($address, $limit, $offset);
echo $address_info->transactions[1]->version;
