### ISSUE TITLE
blockchain api address balance error

### ISSUE THREAD

**Issue by soorajlal** [blockchain/api-v1-client-php#28]
Hi i am using blockchain api(v1) for my website. 
I wrote a script to get balance of specific bitcoin address 

> <?php
> // Include the autoload.php from its vendor directory
> require 'vendor/autoload.php';
> $api_code = 'my-api-key';
> // Create the base Blockchain class instance
> $Blockchain = new \Blockchain\Blockchain($api_code);
> //get current wallet
> $Blockchain->Wallet->credentials('wallet-id ', 'password');
> $balance = $Blockchain->Wallet->getAddressBalance('bitcoin-address');
> print_r($balance);
> ?>

But i got these error:

> [Mon Nov 30 14:13:19.010535 2015] [:error] [pid 17154] [client 127.0.0.1:60335] PHP Fatal error:  Uncaught exception 'Blockchain\Exception\ApiError' with message 'Unknown Key Format' in /var/www/html/blockchain-php/src/Blockchain.php:99\nStack trace:\n#0 /var/www/html/blockchain-php/src/Wallet/Wallet.php(47): Blockchain\Blockchain->post('merchant/820541...', Array)\n#1 /var/www/html/blockchain-php/src/Wallet/Wallet.php(60): Blockchain\Wallet\Wallet->call('address_balance', Array)\n#2 /var/www/html/blockchain-php/wallet.php(30): Blockchain\Wallet\Wallet->getAddressBalance('12vzUiRrd3oqbzH...')\n#3 {main}\n  thrown in /var/www/html/blockchain-php/src/Blockchain.php on line 99

How to solve this error. Please Help.

Thanks in advance.

**Comment by ioncibotaru** [comment]
Same error here, please tell if you found a solution.
Thanks.

**Comment by icibotaru** [comment]
I found my problem, maybe you have the same.
In my case i was using my Blockchain address that they give when we login, but that is not the key.
The key is the Identifier the one you use to login.

Good luck!

**Comment by sharayuS** [comment]
Okay..But how to obtain this key?

**Comment by icibotaru** [comment]
First, make a wallet on Blockchain, then you will get and email telling that this is your Login Link: https://blockchain.info/wallet/indetifier_goes_here
Now you have the identifier and the password is the one you wrote when you created the account.

Now that the API knows you by the identifier and the password you can make requests.

**Comment by sharayuS** [comment]
Hey....First of all Thanku
Yaa..I have already done with this procedure and got everything required
and also made request for api key..and its been more than 24 hr,haven't got
any reply yet..:(

**Comment by sharayuS** [comment]
And one more thing what does URL field actually required bcoz i havent made
my web application remote yet..Its still running on Localhost server??

**Comment by icibotaru** [comment]
If you use api-v1-client-php library then you don't need to know the url structure, just the functions that are there to make it all easy.
But for the url structures, take a look here: https://blockchain.info/api
API key is not mandatory, you can request a api key only when you start to have more requests then normal. If you insist on getting a API Key and still no answer in 48 hours then use https://blockchain.zendesk.com/home i'm sure the support team will help you.

**Comment by sharayuS** [comment]
Yes i am using the same library (api-v1-client-php)
But there this code for pushing raw transaction on network which requires
api_code..What should put there?

<?php

   require_once('src/Blockchain.php');


   $Blockchain = new \Blockchain\Blockchain($api_code);

    $tx="69206c6f76652072616e626972";

 try{

    $Blockchain->Push->TX($tx);

}catch(Blockchain_Error $e)
{
     echo $e->getMessage();
}

?>

bcoz it giving me error->*Fatal error*: Class 'Blockchain\Create\Create'
not found in *C:\xampp2\htdocs\eboxapi\src\Blockchain.php* on line *65*

*And does it require Composer?*

**Comment by Lalitpatadiya12** [comment]
I have same error see below 

Uncaught exception 'Blockchain\Exception\ApiError' with message 'Error building transaction' in /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/vendor/apiv1/src/Blockchain.php:117 Stack trace: #0 /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/vendor/apiv1/src/Wallet/Wallet.php(47): Blockchain\Blockchain->post('merchant/2ea850...', Array) #1 /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/vendor/apiv1/src/Wallet/Wallet.php(122): Blockchain\Wallet\Wallet->call('payment', Array) #2 /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/application/modules/web_service/controllers/web_service.php(2729): Blockchain\Wallet\Wallet->send('12326Ha3LSLbN5K...', 0.001, '1') #3 [internal function]: Web_service->person_bit_send() #4 /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/bonfire/codeigniter/core/CodeIgniter.php(363): call_user_func_array(Array, Array) #5 /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/public/index.php(567): require_once('/var/www/vhosts...') #6 {main} thrown in /var/www/vhosts/webcluesglobal.com/httpdocs/qa/digypay/vendor/apiv1/src/Blockchain.php on line 117

Can you please guid me
