### ISSUE TITLE
Unable to decode JSON response from Blockchain

### ISSUE THREAD

**Issue by pagito** [blockchain/api-v1-client-php#30]
Hi, 

I'm getting error: 'Unable to decode JSON response from Blockchain'. Any suggestions? I'm using composer.

**Comment by pagito** [comment]
Do I need api key? If yes, where I can get it?

**Comment by pagito** [comment]
I reopened that issue, because still getting the same error.
**Fatal error:  Uncaught exception 'Blockchain\Exception\Error' with message 'Unable to decode JSON response from Blockchain: <!DOCTYPE html>**



 <html class="no-js" lang="en-US"> 
<head>
<title>Access denied | blockchain.info used CloudFlare to restrict access</title>
.........................

The same code works properly on localhost. After uploading on the server something goes wrong.
I got API key, but I guess there is no need for that, because on my local machine I'm not passing any key. 

Thanks in advance !

**Comment by clarkmoody** [comment]
What API call are you making, and how fast are you making requests?

**Comment by pagito** [comment]
I'm making Exchange Rates API, and trying to lunch example - rates.php with default configuration.

**Comment by sharayuS** [comment]
Fatal error: Class 'Blockchain\Create\Create' not found in C:\xampp3\htdocs\Wallet\src\Blockchain.php on line 65

**Comment by sharayuS** [comment]
PHP Fatal error:  Uncaught exception 'Blockchain\Exception\Error' with message 'Unable to decode JSON response from Blockchain: Authorization Key invalid or disabled' in /home/sharayu/Desktop/EBox/Wallet/src/Blockchain.php:157
Stack trace:
#0 /home/sharayu/Desktop/EBox/Wallet/src/Blockchain.php(122): Blockchain\Blockchain->_call()
#1 /home/sharayu/Desktop/EBox/Wallet/src/Create/Create.php(39): Blockchain\Blockchain->post('api/v2/create_w...', Array)
#2 /home/sharayu/Desktop/EBox/Wallet/src/Create/Create.php(14): Blockchain\Create\Create->doCreate('sharayushinde88...', NULL, NULL, NULL)
#3 /home/sharayu/Desktop/EBox/Wallet/trywn.php(22): Blockchain\Create\Create->create('sharayushinde88...', NULL, NULL)
#4 {main}

**Comment by pagito** [comment]
Didn't change anything and now it's working !

**Comment by poojadiyo** [comment]
Hi
I'm getting error like below ,

**Fatal error: Uncaught exception 'Blockchain\Exception\Error' with message 'Unable to decode JSON response from Blockchain:** 

I will getting same error in localhost  as well as server.

Thanks in Advance !!!

**Comment by GautamArya** [comment]
I have am trying to create a wallet using `$Blockchain->Create->create` function. I have used the recommended API ( [my wallet service v3](https://github.com/blockchain/service-my-wallet-v3/) ) for this. but getting the following error:

`Unable to decode JSON response from Blockchain: <!DOCTYPE html><html> <head> <title>Blockchain API: Bitcoin API - Blockchain</title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"><link rel="stylesheet" href="/Resources/overrides.min.css?6101b64e7dd24bd0"><script src="/Resources/js/jquery.min.js" type="text/javascript"></script><script type="text/javascript" src="/Resources/js/bootstrap.min.js?6101b64e7dd24bd0"></script><script src="/Resources/js/shared.min.js?6101b64e7dd24… <a href="https://www.linkedin.com/company/blockchain" rel="noreferrer nofollow" target="_blank"> <img alt="LinkedIn Icon" src="/Resources/linkedin-footer-logo.svg"> </a> <a href="https://www.facebook.com/blockchain/" rel="noreferrer nofollow" target="_blank"> <img alt="Facebook Icon" src="/Resources/facebook-footer-logo.svg"> </a> </div> </div> </footer> <script type="text/javascript" src="/Resources/js/api-index.js"></script> </body> </html> `

Can anybody help? Am I doing something wrong? Is this an issue from API side?
