### ISSUE TITLE
API code not received

### ISSUE THREAD

**Issue by jayashree-saraf** [blockchain/api-v1-client-php#31]
I'm trying to obtain api code but is not getting responded because it require an URL, and I don't have any . What to do?

**Comment by narthex** [comment]
They discontinued the original API 1st Jan 2016 so you have to sign up via a different address: https://api.blockchain.info/v2/apikey/request/

Note that we had to submit 3 times and put in a support ticket to get a response

**Comment by jayashree-saraf** [comment]
But they are asking for url of website or application? SO what should be specifies. As my website is not online yet
