### ISSUE TITLE
Unable to decode JSON response

### ISSUE THREAD

**Issue by sharayuS** [blockchain/api-v1-client-php#32]
PHP Fatal error:  Uncaught exception 'Blockchain\Exception\Error' with message 'Unable to decode JSON response from Blockchain: Authorization Key invalid or disabled' in /home/sharayu/Desktop/EBox/Wallet/src/Blockchain.php:157
Stack trace:
#0 /home/sharayu/Desktop/EBox/Wallet/src/Blockchain.php(122): Blockchain\Blockchain->_call()
#1 /home/sharayu/Desktop/EBox/Wallet/src/Create/Create.php(39): Blockchain\Blockchain->post('api/v2/create_w...', Array)
#2 /home/sharayu/Desktop/EBox/Wallet/src/Create/Create.php(14): Blockchain\Create\Create->doCreate('sharayushinde88...', NULL, NULL, NULL)
#3 /home/sharayu/Desktop/EBox/Wallet/trywn.php(22): Blockchain\Create\Create->create('sharayushinde88...', NULL, NULL)
#4 {main}

**Comment by sp111** [comment]
I am getting the same error. After debugging I have found that in Create.php 
`$this->blockchain->post('api/v2/**create_wallet**', $params)`

But in Blockchain.php's post function 'resource' is compared with only 'create'. When I changed that to 'create_wallet' it started working.
 `if ((**$resource == "api/v2/create"**) || (substr($resource, 0, 8) === "merchant")) {
            if ($this->service_url == null) {
                throw new ApiError("When calling a merchant endpoint or creating a wallet, service_url must be set");
            }
            $url = $this->service_url;
        }`

Can you tell me if I got this right? If not, please suggest me a solution.

Thank you.

**Comment by assafY** [comment]
Yes - that is the correct solution. Thanks! Would you like to submit a PR with that change?

**Comment by sp111** [comment]
Yes, I would like to submit the PR.

**Comment by assafY** [comment]
Thanks, however I have had another look this morning, and it seems that the solution should be leaving `Blockchain.php` as it is, but changing the following line in `Create.php`:

`return new WalletResponse($this->blockchain->post('api/v2/create_wallet', $params));`

to:

`return new WalletResponse($this->blockchain->post('api/v2/create', $params));`

Can you please confirm whether this works for you, and update the PR?

**Comment by sp111** [comment]
Ok, I will check that and update PR.

**Comment by sp111** [comment]
Yes, it's working. I will submit updated PR.

**Comment by assafY** [comment]
Merged. Thank you once again for your help.

**Comment by assafY** [comment]
Congrats!
