### ISSUE TITLE
v1 discontinued, what now ?

### ISSUE THREAD

**Issue by PavelNiedoba** [blockchain/api-v1-client-php#34]
Today I found out, that this api was discontinued. I'm looking for replacement. I found new api, but it's using NodeJs. More than that there are notes, that java should be installed to decrypt wallets. I don't like the idea of using other languages. Is there or will there be a way how to use v2 api with php only ? I'm mainly interested in send api.

**Comment by narthex** [comment]
Try blocktrail.com
