### ISSUE TITLE
No result for some address

### ISSUE THREAD

**Issue by anieshjoseph** [blockchain/api-v1-client-php#35]
Not getting any result for some address when I used "Explorer->getAddress()". PHP shows "php memory exhausted error" and I added the code below to fix this.

 `ini_set('memory_limit', '-1');`

Now it shows "Internal server error". What I understand is, some address is taking too much time and not returning any result. 

Is there any solution ?

Can I add a maximum execution time to solve this issue to either Blockchain API or in PHP ?

**Comment by alecalve** [comment]
What address causes this errors?

**Comment by anieshjoseph** [comment]
19ZZ8DZsb5qgchuKPZWET7Uj8rDoj4KgmB
17RTTUAiiPqUTKtEggJPec8RxLMi2n9EZ9

**Comment by alecalve** [comment]
By using this code
```php
<?php
require __DIR__ . '/vendor/autoload.php';

$Blockchain = new \Blockchain\Blockchain();

$address = "...";
$limit = 1000;
$offset = 0;
$address_info = $Blockchain->Explorer->getAddress($address, $limit, $offset);
echo memory_get_peak_usage() / (1024 * 1024.0) . "\n";
```

with the two addresses you provided, I get peak memory uses of ~31MiB and ~9.8MiB respectively.

Raising ```memory_limit``` to 50MiB should be enough to process these addresses. 

I would recommend you to use the pagination provided by ```$Blockchain->Explorer->getAddress($address, $limit, $offset)``` to lower the memory usage of your script. It enables fetching transactions by packets of ```$limit``` transactions starting at the ```$offset``` nth transaction.

**Comment by anieshjoseph** [comment]
Such addresses shows "Fatal Error: Allowed Memory Size of xx Bytes Exhausted"

To resolve this, I added two lines:

```
set_time_limit(0);
ini_set('memory_limit', '-1');
```

Regarding pagination, I have already set $limit to 50

**Comment by alecalve** [comment]
Maybe lowering ```$limit``` to something like 5 or 10 would remove the need to remove memory and time limitations as the transactions involving the addresses are quite big.

**Comment by anieshjoseph** [comment]
Yes, I have noted that long address list on blockchain official site. But your suggestion to lowering the limit is a good suggestion and I will try with that.

Thank you.

**Comment by anieshjoseph** [comment]
The site is running on GoDaddy. If I change to another hosting or upgrade to higher level, will this resolve the issue permanently ?

**Comment by alecalve** [comment]
It should resolve it, shared hosting providers usually lower the limits on memory use and runtime for PHP scripts.

**Comment by anieshjoseph** [comment]
Okay. Thank you.
