### ISSUE TITLE
How to get status of my transaction..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [blockchain/api-v1-client-php#43]
If I am sent 0.001 btc from my wallet to another address is successfully run but how can I get the status of that transaction.

Status means transaction is in which mode like pending,success,fails...etc

Using bellow code I found the whole discription of the transaction but not found the status of that transaction
                  $tx = $Blockchain->Explorer->getTransaction($hash);

Is it possible to get status ..?

**Comment by assafY** [comment]
I assume that by status you mean number of confirmations?

Usually a transaction can safely be regarded as 'successful' if it has 3 confirmations or more. The tx object in this api client does not have a field containing the number of confirmations, but you can look at the height of the block containing the transaction:

```php
$latest_block_height = $Blockchain->Explorer->getLatestBlock()->height;
$tx_height = $Blockchain->Explorer->getTransaction($hash).block_height;
$num_of_confirmations = $latest_block_height - $tx_height + 1;
```
