### ISSUE TITLE
Clarification:  public $n_btc_mined;

### ISSUE THREAD

**Issue by ErikThiart** [blockchain/api-v1-client-php#44]
Hi, can someone please clarify to me what this actually is? I took it that that is the total amount of bitcoins ever mined to date ( 24 hour delayed )

However upon looking at the value of $n_btc_mined -  1,900.00000000

That cannot be all the bitcoins ever mined. So, can someone just give me a recap what $n_btc_mined represents and then, can we update the documentation to add some clarity.

Much love from South Africa

**Comment by assafY** [comment]
Hey @ErikThiart 

The value represents the total btc mined in the last 24 hours.

Much love from the UK ;)
