### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by c88lopez** [blockchain/api-v1-client-php#6]
It would be nice that this api could be installed using composer. 

If accepted, I could make the necessary changes to make it happen.

**Comment by KMHouk** [comment]
What changes would that entitle (and at a cost)?

Making this api available through composer is something we would be interested in, so it will be done eventually.

**Comment by c88lopez** [comment]
is there any ETA for this?

**Comment by KMHouk** [comment]
Hi,

Can you test and see if the project works with composer? We pushed support to the dev branch

https://github.com/blockchain/api-v1-client-php/tree/dev

**Comment by c88lopez** [comment]
Sorry if I misunderstood but you want me to make this possible?

If so I'll fork it and start working.

**Comment by KMHouk** [comment]
Hm, alright. So does this mean each php file needs its own folder? And is the directory 'src' required, or can we specify our current 'lib' directory?

In order to get this right, would you be willing to fork this lib and create a pull request with the necessary changes?

**Comment by c88lopez** [comment]
All php file which contains a class needs a namespace. These files only contains the class.
I think we can specify the 'lib' directory as the source, it is a configuration on the composer.json file.

I could make the changes, you will get a merge request soon.

**Comment by KMHouk** [comment]
Awesome, thanks! When you make the pull request I'll look it over, merge, and update with packagist
